### ISSUE TITLE
mutableItems is private

### ISSUE THREAD

**Issue by mhashim6** [tgirard12/KRecyclerDsl#7]
Intellij complains that mutableItems is declared private in DataClassAdapter in the current version 0.3.0. this makes it impossible to edit items once inserted.

**Comment by tgirard12** [comment]
You are right, I have remove the private visibility after releasing v0.3.0.
I will publish a fix version as soon as possible.

**Comment by tgirard12** [comment]
Hi, v0.4.0 is available
